# Generated by Django 4.2.6 on 2023-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
