# Generated by Django 4.2.6 on 2023-11-11 23:19

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_description_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='static/images/uploads', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
