# Generated by Django 4.2.6 on 2023-12-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date_time_of_publication',)},
        ),
    ]
