# Generated by Django 4.2.7 on 2023-11-26 20:37

from django.db import migrations, models
import forms_project.forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(error_messages={'over_18': 'User must not be over 18!'}, validators=[forms_project.forms.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=15, validators=[forms_project.forms.validators.validate_name]),
        ),
    ]
